# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RQizarIGsBP4rtcDt0LpPLAhtwX9mngi
"""


import spacy
import random
import time

nlp = spacy.load("pt_core_news_sm")

produtos = {
    "celular": ["Apple iPhone 14", "Samsung Galaxy S23", "Motorola Edge 30 Neo"],
    "notebook": ["Dell XPS 13 Plus", "Apple Macbook Air M2", "Lenovo ThinkPad X1 Carbon"],
    "acessório": ["Fone Bluetooth JBL Tune 510BT", "Carregador Turbo Samsung 25W", "Mouse Gamer Logitech G203"]
}

faq = {
    "localizacao": "📍 Nossa loja está localizada na Rua do Sol, nº 266 - Recife - PE , CEP: 52320-560.",
    "horario": "🕒 Nosso horário de atendimento é de segunda a sexta, das 08h00 às 18h00, e aos sábados das 08h00 às 12h00.",
    "suporte": "🛠️ Para suporte técnico, entre em contato pelo e-mail: suporte@endolog.com ou pelo telefone (81) 4002-9230.",
    "status_pedido": "📦 Para consultar o status do seu pedido, acesse nosso site na seção 'Meus Pedidos' ou fale com um atendente."
}

def saudacao():
    print("=" * 60)
    print("🤖  Bem-vindo(a) à *EndoLog Store - Assistente Virtual*")
    print("Estamos aqui para proporcionar a melhor experiência de compra.")
    print("=" * 60)
    print("\nPor favor, selecione uma das opções ou envie sua pergunta:")
    print("""
    🛒  Consultar produtos
    🎯  Receber recomendações
    📍  Localização da loja
    🕒  Horário de funcionamento
    🛠️  Suporte técnico
    📦  Consultar status de pedido
    👨‍💼  Falar com um atendente humano
    ❌  Encerrar atendimento
    """)
    print("=" * 60)

def entender_intencao(texto):
    texto = texto.lower()

    if any(p in texto for p in ["oi", "olá", "bom dia", "boa tarde", "boa noite"]):
        return "saudacao"

    elif any(p in texto for p in ["produto", "consultar", "tem", "possui", "vender", "vende", "quais produtos", "qual produto"]):
        return "consultar_produto"

    elif any(p in texto for p in ["recomenda", "sugestão", "indica", "qual é o melhor", "me sugere"]):
        return "recomendacao"

    elif any(p in texto for p in ["onde fica", "localização", "endereço", "como chegar"]):
        return "localizacao"

    elif any(p in texto for p in ["horário", "funciona", "que horas", "aberto", "atendimento"]):
        return "horario"

    elif any(p in texto for p in ["suporte", "assistência", "ajuda técnica", "problema", "manutenção"]):
        return "suporte"

    elif any(p in texto for p in ["pedido", "status", "acompanhar", "rastreamento", "meu pedido"]):
        return "status_pedido"

    elif any(p in texto for p in ["atendente", "humano", "pessoa", "falar com alguém", "alguém"]):
        return "atendente"

    elif any(p in texto for p in ["sair", "encerrar", "fim", "tchau", "obrigado"]):
        return "encerrar"

    elif any(p in texto for p in ["ajuda", "menu", "opções", "opcao", "opções"]):
        return "ajuda"

    else:
        return "desconhecido"

def consultar_produto():
    print("\n🔍 Confira nossos produtos disponíveis no momento:\n")
    for categoria, itens in produtos.items():
        print(f"🗂️  {categoria.capitalize()}:")
        for item in itens:
            print(f"   - {item}")
    print("-" * 50)

def recomendar_produto():
    print("\n🎯 Para te ajudar melhor, qual categoria você prefere? (celular, notebook ou acessório)")
    while True:
        categoria = input("Digite a categoria desejada: ").strip().lower()

        categorias_validas = produtos.keys()
        if categoria in categorias_validas:
            time.sleep(1)
            recomendado = random.choice(produtos[categoria])
            print(f"\n👍 Ótima escolha! Baseado na categoria '{categoria}', recomendamos: *{recomendado}*.\n")
            break
        else:
            print("❌ Não reconheci essa categoria. Por favor, escolha entre: celular, notebook ou acessório.")

def mostrar_faq(chave):
    respostas = {
        "localizacao": [
            "📍 Nossa loja fica na Rua do Sol, nº 266 - Recife - PE, CEP: 53250-320.",
            "🏠 Você pode nos encontrar na Rua do Sol,nº 266 - Recife - PE"
        ],
        "horario": [
            "🕒 Funcionamos de segunda a sexta das 08h às 18h e aos sábados das 08h às 12h.",
            "⏰ Nosso horário é de seg a sex, 08:00 - 18:00, e sábado até meio-dia."
        ],
        "suporte": [
            "🛠️ Para suporte, envie e-mail para suporte@endolog.com ou ligue (81) 4002-9130.",
            "☎️ Suporte técnico pelo telefone (81) 4002-9130 ou email suporte@endolog.com."
        ],
        "status_pedido": [
            "📦 Para consultar seu pedido, acesse a seção 'Meus Pedidos' no nosso site ou fale com um atendente.",
            "📲 Você pode acompanhar seu pedido na área 'Meus Pedidos' do nosso site."
        ]
    }

    resposta = random.choice(respostas.get(chave, ["Desculpe, não tenho essa informação."]))
    print(f"\n{resposta}\n")

def iniciar_chatbot():
    saudacao()

    while True:
        texto = input("\nVocê: ").strip()
        intencao = entender_intencao(texto)

        if intencao == "saudacao":
            respostas = [
                "🤖 Olá novamente! Em que posso ajudá-lo(a)?",
                "👋 Seja bem-vindo(a) de volta! Como posso ajudar?",
                "😀 Estou aqui para ajudar. O que deseja saber?"
            ]
            print(random.choice(respostas))

        elif intencao == "consultar_produto":
            print("Um momento, vou listar os produtos para você...")
            time.sleep(1.2)
            consultar_produto()

        elif intencao == "recomendacao":
            recomendar_produto()

        elif intencao == "localizacao":
            mostrar_faq("localizacao")

        elif intencao == "horario":
            mostrar_faq("horario")

        elif intencao == "suporte":
            mostrar_faq("suporte")

        elif intencao == "status_pedido":
            mostrar_faq("status_pedido")

        elif intencao == "atendente":
            print("\n📞 Transferindo para um atendente humano... Por favor, aguarde um momento.\n")
            break

        elif intencao == "encerrar":
            print("\n👋 Agradecemos muito sua visita à EndoLog Store.")
            print("Estamos sempre prontos para ajudar. Tenha um ótimo dia!\n")
            break

        elif intencao == "ajuda":
            print("\nAqui estão as opções disponíveis para você:")
            saudacao()

        else:
            respostas_desconhecidas = [
                "❓ Não entendi muito bem. Poderia reformular sua pergunta?",
                "🤔 Não consegui compreender. Por favor, tente de outra forma.",
                "😕 Desculpe, não sei responder isso. Que tal escolher uma das opções do menu?"
            ]
            print(random.choice(respostas_desconhecidas))
            time.sleep(1)
            print("Se precisar, digite 'ajuda' para ver as opções novamente.")

iniciar_chatbot()